#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="${NOVAADAPT_GITHUB_REPO:-maddwiz/NovaAdapt}"
SIGNING_ENV_DEFAULT="$HOME/.novaadapt/android/novaadapt-operator-signing.env"
SIGNING_ENV_FILE="${NOVAADAPT_ANDROID_SIGNING_ENV:-$SIGNING_ENV_DEFAULT}"
PLAY_SERVICE_JSON=""
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage:
  ./scripts/configure_android_github_secrets.sh [--repo owner/name] [--signing-env /path/to/env] [--play-service-json /path/to/service-account.json] [--dry-run]

Configures the GitHub Actions secrets required by:
  - .github/workflows/android-shell.yml
  - .github/workflows/android-play.yml
  - .github/workflows/release.yml

Required local input:
  - signing env file generated by ./scripts/build_android_shell.sh

Optional input:
  - Google Play service account JSON for Play upload workflow
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      REPO="$2"
      shift 2
      ;;
    --signing-env)
      SIGNING_ENV_FILE="$2"
      shift 2
      ;;
    --play-service-json)
      PLAY_SERVICE_JSON="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$SIGNING_ENV_FILE" ]]; then
  echo "signing env file not found: $SIGNING_ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$SIGNING_ENV_FILE"

required_envs=(
  NOVAADAPT_ANDROID_KEYSTORE_PATH
  NOVAADAPT_ANDROID_KEYSTORE_PASSWORD
  NOVAADAPT_ANDROID_KEY_ALIAS
  NOVAADAPT_ANDROID_KEY_PASSWORD
)
for name in "${required_envs[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "missing value in signing env: $name" >&2
    exit 1
  fi
done

if [[ ! -f "$NOVAADAPT_ANDROID_KEYSTORE_PATH" ]]; then
  echo "keystore file not found: $NOVAADAPT_ANDROID_KEYSTORE_PATH" >&2
  exit 1
fi

set_secret() {
  local name="$1"
  local value="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] would set $name on $REPO"
    return 0
  fi
  gh secret set "$name" -R "$REPO" --body "$value" >/dev/null
  echo "set $name on $REPO"
}

set_secret_file() {
  local name="$1"
  local file_path="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] would set $name from $file_path on $REPO"
    return 0
  fi
  gh secret set "$name" -R "$REPO" < "$file_path"
  echo "set $name on $REPO"
}

KEYSTORE_BASE64="$(python3 - <<'PY' "$NOVAADAPT_ANDROID_KEYSTORE_PATH"
import base64
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
print(base64.b64encode(path.read_bytes()).decode("ascii"))
PY
)"

set_secret "NOVAADAPT_ANDROID_KEYSTORE_BASE64" "$KEYSTORE_BASE64"
set_secret "NOVAADAPT_ANDROID_KEYSTORE_PASSWORD" "$NOVAADAPT_ANDROID_KEYSTORE_PASSWORD"
set_secret "NOVAADAPT_ANDROID_KEY_ALIAS" "$NOVAADAPT_ANDROID_KEY_ALIAS"
set_secret "NOVAADAPT_ANDROID_KEY_PASSWORD" "$NOVAADAPT_ANDROID_KEY_PASSWORD"

if [[ -n "$PLAY_SERVICE_JSON" ]]; then
  if [[ ! -f "$PLAY_SERVICE_JSON" ]]; then
    echo "play service account json not found: $PLAY_SERVICE_JSON" >&2
    exit 1
  fi
  set_secret_file "NOVAADAPT_GOOGLE_PLAY_SERVICE_ACCOUNT_JSON" "$PLAY_SERVICE_JSON"
else
  echo "skipped NOVAADAPT_GOOGLE_PLAY_SERVICE_ACCOUNT_JSON; provide --play-service-json to configure Play upload"
fi
